#!/bin/bash
echo $$ > .pid
ans=1
MODE="+"

usr1() 
{
	MODE="+"
}

usr2()
{
	MODE="*"
}

term() 
{
	MODE="sigterm"
}

trap 'usr1' USR1
trap 'usr2' USR2
trap 'term' SIGTERM

while true;
do 

	case $MODE in 
		"+")
			let ans=$ans+2
			echo $ans
			;;
		"*") 
			let ans=$ans*2
			echo $ans
			;;
		"term")
			echo "Handler was stopped"
			exit
			;;
	esac
	sleep 1s
done

